name: Checks
on:
  workflow_call:
  workflow_dispatch:
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [8]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup

  lint:
    name: Lint
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [8]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint & format code
        run: pnpm format & pnpm lint
        
  foundry:
    name: Foundry
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -ieo pipefail {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        run:
          curl -L https://foundry.paradigm.xyz | bash ; source ~/.bashrc ; foundryup
      - name: Run Anvil Client in background for integration tests
        run: anvil --fork-url ${{ secrets.ETHEREUM_RPC_URL }} &
        env:
          ETHEREUM_RPC_URL: ${{ secrets.ETHEREUM_RPC_URL }}
          POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
  test:
    name: Test
    needs: [install, foundry]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [8]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Test
        run: pnpm test:ci
        env:
          ETHEREUM_RPC_URL: ${{ secrets.ETHEREUM_RPC_URL }}
          POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
  build:
    name: Build
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [8]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm build